name: CD

on:
  push:
    branches: ["master"]
    
permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Create application.yml
      run:
        cd ./src/main/resources
        echo "${{secrets.APPLICATION_YML}}" > application.yml
      shell: bash
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: build with gradle
      run: ./gradlew build
      
    - name: Create and Push Image to Docker Hub
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build --tag ${{secrets.DOCKER_USERNAME}}/BatchApplication:ProductManagement .
        docker push ${{secrets.DOCKER_USERNAME}}/BatchApplication:ProductManagement
        
    - name: Pull image and run
      uses: appleboy/ssh-action@master
      with:
        host: 54.180.71.246
        username: ubuntu
        password: ${{secrets.EC2_PASSWORD}}
        scripts: |
          docker pull ${{secrets.DOCKER_USERNAME}}/BatchApplication:ProductManagement
          docker stop BatchApplication
          docker run -d --rm --name BatchApplication -p 80:8081 ${{secrets.DOCKER_USERNAME}}/BatchApplication:ProductManagement
